language: python
python:
  - "3.2"
before_install:
  - sudo apt-get install mercurial
  - hg clone https://bitbucket.org/pygame/pygame
  - cd pygame
  - sudo apt-get install python3-dev python3-numpy libsdl-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsmpeg-dev libportmidi-dev libavformat-dev libswscale-dev libjpeg-dev libfreetype6-dev
  - python3 setup.py build
  - sudo python3 setup.py install
  - cd ..
# command to install dependencies
install:
  - "pip3 install mutagen"
  - "pip3 install easygui"
  - "pip3 install pylast"
# command to run tests
script: "nosetests Master/*.py"
virtualenv:
  system_site_packages: true